export enum NotificationTypeEnum {
    ALOLINE_RESTAURANT_MARKETING_BEER = 331,
    ALOLINE_RESTAURANT_MARKETING_GIFT = 332, 
	ALOLINE_RESTAURANT_MARKETING_LINK = 333, 
	ALOLINE_RESTAURANT_MARKETING_CONTENT = 334,
}